"""
C162: Causal Bandit -- Composing C161 (Causal Inference) + C146 (Reinforcement Learning)

Bandits that leverage causal knowledge for better exploration/exploitation.
When the reward-generating process has causal structure (confounders, mediators,
instruments), standard bandits are suboptimal. Causal bandits use graph structure
to identify optimal interventions, handle confounding, and reason counterfactually.

Components:
1. CausalBanditEnv -- Environment with causal DAG generating rewards
2. CausalUCB -- UCB with causal bounds (tighter confidence via do-calculus)
3. CausalThompsonSampling -- Thompson sampling with causal priors
4. InterventionalBandit -- Can intervene on intermediate variables
5. TransferBandit -- Transfer causal knowledge across related environments
6. CounterfactualBandit -- Uses counterfactual reasoning for regret minimization
7. CausalLinUCB -- Linear contextual bandit with causal feature selection
8. BudgetedCausalBandit -- Interventions have costs, optimize net reward
9. CausalBanditAnalyzer -- Regret analysis and comparison tools
"""

import sys
import os
import math
import random
from copy import deepcopy
from collections import defaultdict

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'C161_causal_inference'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'C146_reinforcement_learning'))

from causal_inference import (
    CausalGraph, Intervention, BackdoorCriterion, FrontdoorCriterion,
    DoCalculus, CounterfactualEngine, CausalUtils, Factor
)


# ============================================================
# 1. CausalBanditEnv
# ============================================================

class CausalBanditEnv:
    """Bandit environment where rewards are generated by a causal DAG.

    Arms correspond to interventions on a treatment variable.
    Confounders, mediators, and other causal structure affect rewards.
    The agent can observe some variables but must reason about hidden ones.
    """

    def __init__(self, graph, treatment, outcome, observable=None, seed=None):
        """
        Args:
            graph: CausalGraph with CPDs defining the data-generating process
            treatment: name of the treatment variable (arms = its values)
            outcome: name of the outcome/reward variable
            observable: set of variables the agent can observe (None = all non-treatment/outcome)
            seed: random seed
        """
        self.graph = graph
        self.treatment = treatment
        self.outcome = outcome
        self.k = graph.cardinalities.get(treatment, 2)  # number of arms
        self.rng = random.Random(seed)

        if observable is None:
            self.observable = set(graph.nodes) - {treatment, outcome}
        else:
            self.observable = set(observable)

        # Precompute topological order for sampling
        self._topo_order = graph.topological_sort()
        self._true_arm_rewards = self._compute_true_rewards()

    def _compute_true_rewards(self):
        """Compute E[Y | do(X=a)] for each arm a."""
        rewards = []
        for a in range(self.k):
            factor = self.graph.interventional_query(
                self.outcome, {self.treatment: a}
            )
            # Expected value: sum over outcome values weighted by probability
            ev = 0.0
            card = self.graph.cardinalities.get(self.outcome, 2)
            for val in range(card):
                ev += val * factor.get_value({self.outcome: val})
            rewards.append(ev)
        return rewards

    def optimal_arm(self):
        """Return the arm with highest true expected reward under do()."""
        return max(range(self.k), key=lambda a: self._true_arm_rewards[a])

    def optimal_reward(self):
        """Return the expected reward of the optimal arm."""
        return self._true_arm_rewards[self.optimal_arm()]

    def pull(self, arm):
        """Pull an arm (intervene on treatment=arm), return (context, reward).

        context: dict of observable variable values (sampled from the SCM)
        reward: sampled outcome value
        """
        # Sample from mutilated graph (do(treatment=arm))
        mutilated = self.graph.mutilate({self.treatment: arm})
        sample = self._sample_from_graph(mutilated, {self.treatment: arm})
        context = {v: sample[v] for v in self.observable if v in sample}
        reward = sample[self.outcome]
        return context, reward

    def observe(self):
        """Observe a data point from the observational distribution (no intervention).

        Returns: dict of all variable values sampled from the original graph.
        """
        return self._sample_from_graph(self.graph, {})

    def _sample_from_graph(self, graph, fixed):
        """Sample all variables from graph given fixed values."""
        sample = dict(fixed)
        for node in self._topo_order:
            if node in sample:
                continue
            parents = graph.get_parents(node)
            if node in graph.cpds:
                cpd = graph.cpds[node]
                # Build parent assignment
                parent_assignment = {p: sample[p] for p in parents if p in sample}
                # Get conditional distribution
                card = graph.cardinalities.get(node, 2)
                probs = []
                for val in range(card):
                    assignment = dict(parent_assignment)
                    assignment[node] = val
                    probs.append(cpd.get_value(assignment))
                # Normalize
                total = sum(probs)
                if total > 0:
                    probs = [p / total for p in probs]
                else:
                    probs = [1.0 / card] * card
                # Sample
                r = self.rng.random()
                cumulative = 0.0
                sampled_val = card - 1
                for val, p in enumerate(probs):
                    cumulative += p
                    if r < cumulative:
                        sampled_val = val
                        break
                sample[node] = sampled_val
            else:
                # No CPD -- sample uniformly
                card = graph.cardinalities.get(node, 2)
                sample[node] = self.rng.randint(0, card - 1)
        return sample

    def true_reward(self, arm):
        """Return E[Y | do(X=arm)]."""
        return self._true_arm_rewards[arm]


# ============================================================
# 2. CausalUCB
# ============================================================

class CausalUCB:
    """UCB bandit that uses causal bounds for tighter confidence intervals.

    When confounders exist, the observational mean != interventional mean.
    CausalUCB uses the backdoor/frontdoor criterion to adjust estimates,
    giving tighter bounds than standard UCB which ignores confounding.
    """

    def __init__(self, env, c=2.0):
        self.env = env
        self.k = env.k
        self.c = c
        self.counts = [0] * self.k
        self.reward_sums = [0.0] * self.k
        self.total = 0

        # Check if backdoor adjustment is possible
        self.adjustment_set = BackdoorCriterion.find_adjustment_set(
            env.graph, env.treatment, env.outcome
        )
        self.use_causal = self.adjustment_set is not None

        # Track stratified counts for adjustment
        if self.use_causal:
            # For each arm, track reward by adjustment set values
            self._strat_counts = defaultdict(lambda: defaultdict(int))
            self._strat_reward_sums = defaultdict(lambda: defaultdict(float))

    def select_arm(self):
        """Select arm using causal UCB criterion."""
        # Explore unvisited arms first
        for a in range(self.k):
            if self.counts[a] == 0:
                return a

        ucb_values = []
        for a in range(self.k):
            if self.use_causal:
                mean = self._adjusted_mean(a)
            else:
                mean = self.reward_sums[a] / self.counts[a]
            bonus = self.c * math.sqrt(math.log(self.total) / self.counts[a])
            ucb_values.append(mean + bonus)
        return max(range(self.k), key=lambda a: ucb_values[a])

    def _adjusted_mean(self, arm):
        """Compute backdoor-adjusted mean reward for an arm."""
        if self.counts[arm] == 0:
            return 0.0

        # Weighted average over adjustment set strata
        strat_counts = self._strat_counts[arm]
        strat_rewards = self._strat_reward_sums[arm]
        total_strat = sum(strat_counts.values())
        if total_strat == 0:
            return self.reward_sums[arm] / max(1, self.counts[arm])

        # Weight by marginal distribution of adjustment variables
        weighted_sum = 0.0
        total_weight = 0.0
        for key, count in strat_counts.items():
            if count > 0:
                mean_in_stratum = strat_rewards[key] / count
                weight = count  # Use empirical frequency as weight
                weighted_sum += mean_in_stratum * weight
                total_weight += weight

        return weighted_sum / total_weight if total_weight > 0 else 0.0

    def update(self, arm, context, reward):
        """Update estimates after pulling arm."""
        self.counts[arm] += 1
        self.reward_sums[arm] += reward
        self.total += 1

        if self.use_causal and context:
            # Stratify by adjustment set values
            key = tuple(sorted(
                (v, context[v]) for v in self.adjustment_set if v in context
            ))
            self._strat_counts[arm][key] += 1
            self._strat_reward_sums[arm][key] += reward

    def run(self, n_rounds):
        """Run for n_rounds, return (arms_chosen, rewards, cumulative_regret)."""
        arms = []
        rewards = []
        regret = []
        cum_regret = 0.0
        opt_reward = self.env.optimal_reward()

        for _ in range(n_rounds):
            arm = self.select_arm()
            context, reward = self.env.pull(arm)
            self.update(arm, context, reward)
            arms.append(arm)
            rewards.append(reward)
            cum_regret += opt_reward - self.env.true_reward(arm)
            regret.append(cum_regret)

        return arms, rewards, regret


# ============================================================
# 3. CausalThompsonSampling
# ============================================================

class CausalThompsonSampling:
    """Thompson sampling with causal priors.

    Uses causal graph structure to set informative priors on arm rewards.
    When an arm's effect is identifiable via do-calculus, uses the causal
    effect estimate to initialize the prior, accelerating convergence.
    """

    def __init__(self, env, prior_strength=1.0):
        self.env = env
        self.k = env.k
        self.rng = random.Random(42)
        self.prior_strength = prior_strength

        # Beta distribution parameters (for binary rewards)
        self.alphas = [1.0] * self.k
        self.betas = [1.0] * self.k

        # Try to set causal priors
        self._set_causal_priors()

    def _set_causal_priors(self):
        """Use causal effect estimates to set informative priors."""
        try:
            adjustment_set = BackdoorCriterion.find_adjustment_set(
                self.env.graph, self.env.treatment, self.env.outcome
            )
            if adjustment_set is not None:
                for arm in range(self.k):
                    factor = self.env.graph.interventional_query(
                        self.env.outcome, {self.env.treatment: arm}
                    )
                    # Get P(Y=1 | do(X=arm))
                    p = factor.get_value({self.env.outcome: 1})
                    # Set prior proportional to causal estimate
                    n = self.prior_strength * 10
                    self.alphas[arm] = 1.0 + p * n
                    self.betas[arm] = 1.0 + (1 - p) * n
        except Exception:
            pass  # Fall back to uniform priors

    def select_arm(self):
        """Sample from posterior and pick highest."""
        samples = []
        for a in range(self.k):
            # Beta distribution sampling via inverse transform
            sample = self._beta_sample(self.alphas[a], self.betas[a])
            samples.append(sample)
        return max(range(self.k), key=lambda a: samples[a])

    def _beta_sample(self, alpha, beta_param):
        """Sample from Beta(alpha, beta) using gamma variates."""
        # Use Python's random.gammavariate
        x = self.rng.gammavariate(alpha, 1.0)
        y = self.rng.gammavariate(beta_param, 1.0)
        return x / (x + y) if (x + y) > 0 else 0.5

    def update(self, arm, reward):
        """Update posterior after observing reward."""
        if reward > 0:
            self.alphas[arm] += 1.0
        else:
            self.betas[arm] += 1.0

    def run(self, n_rounds):
        """Run for n_rounds."""
        arms = []
        rewards = []
        regret = []
        cum_regret = 0.0
        opt_reward = self.env.optimal_reward()

        for _ in range(n_rounds):
            arm = self.select_arm()
            _, reward = self.env.pull(arm)
            self.update(arm, reward)
            arms.append(arm)
            rewards.append(reward)
            cum_regret += opt_reward - self.env.true_reward(arm)
            regret.append(cum_regret)

        return arms, rewards, regret


# ============================================================
# 4. InterventionalBandit
# ============================================================

class InterventionalBandit:
    """Bandit that can intervene on intermediate causal variables, not just treatment.

    In a causal graph X -> M -> Y with confounder U -> {X, Y},
    intervening on M (the mediator) can bypass confounding.
    This bandit discovers which intervention targets yield best rewards.
    """

    def __init__(self, graph, outcome, interventional_vars=None, seed=None):
        """
        Args:
            graph: CausalGraph
            outcome: reward variable
            interventional_vars: list of variables we can intervene on
                                 (None = all non-outcome nodes)
        """
        self.graph = graph
        self.outcome = outcome
        self.rng = random.Random(seed)

        if interventional_vars is None:
            self.interventional_vars = [n for n in graph.nodes if n != outcome]
        else:
            self.interventional_vars = list(interventional_vars)

        # Build action space: all (variable, value) intervention pairs
        self.actions = []
        for var in self.interventional_vars:
            card = graph.cardinalities.get(var, 2)
            for val in range(card):
                self.actions.append((var, val))

        self.k = len(self.actions)
        self.counts = [0] * self.k
        self.reward_sums = [0.0] * self.k
        self.total = 0

        # Precompute true rewards for each intervention
        self._topo_order = graph.topological_sort()
        self._true_rewards = []
        for var, val in self.actions:
            factor = graph.interventional_query(outcome, {var: val})
            card = graph.cardinalities.get(outcome, 2)
            ev = sum(v * factor.get_value({outcome: v}) for v in range(card))
            self._true_rewards.append(ev)

    def optimal_action(self):
        """Return index of optimal intervention."""
        return max(range(self.k), key=lambda i: self._true_rewards[i])

    def optimal_reward(self):
        return self._true_rewards[self.optimal_action()]

    def select_action(self, c=2.0):
        """UCB-based action selection over interventions."""
        for i in range(self.k):
            if self.counts[i] == 0:
                return i
        ucb = []
        for i in range(self.k):
            mean = self.reward_sums[i] / self.counts[i]
            bonus = c * math.sqrt(math.log(self.total) / self.counts[i])
            ucb.append(mean + bonus)
        return max(range(self.k), key=lambda i: ucb[i])

    def pull(self, action_idx):
        """Execute intervention and observe reward."""
        var, val = self.actions[action_idx]
        mutilated = self.graph.mutilate({var: val})
        env = CausalBanditEnv(mutilated, var, self.outcome, seed=self.rng.randint(0, 10**6))
        # Sample from the mutilated graph
        sample = env._sample_from_graph(mutilated, {var: val})
        return sample[self.outcome]

    def update(self, action_idx, reward):
        self.counts[action_idx] += 1
        self.reward_sums[action_idx] += reward
        self.total += 1

    def run(self, n_rounds, c=2.0):
        """Run for n_rounds."""
        actions = []
        rewards = []
        regret = []
        cum_regret = 0.0
        opt = self.optimal_reward()

        for _ in range(n_rounds):
            idx = self.select_action(c)
            reward = self.pull(idx)
            self.update(idx, reward)
            actions.append(idx)
            rewards.append(reward)
            cum_regret += opt - self._true_rewards[idx]
            regret.append(cum_regret)

        return actions, rewards, regret


# ============================================================
# 5. TransferBandit
# ============================================================

class TransferBandit:
    """Transfer causal knowledge across related bandit environments.

    When two environments share causal structure but differ in parameters,
    knowledge from the source can warm-start learning in the target.
    Uses structural similarity to determine transferability.
    """

    def __init__(self, target_env, source_knowledge=None):
        """
        Args:
            target_env: CausalBanditEnv for the target task
            source_knowledge: dict with keys:
                'arm_estimates': list of (mean, count) per arm
                'graph': CausalGraph of the source
                'adjustment_set': set of adjustment variables
        """
        self.env = target_env
        self.k = target_env.k
        self.counts = [0] * self.k
        self.reward_sums = [0.0] * self.k
        self.total = 0
        self.transfer_weight = 0.0

        if source_knowledge:
            self._apply_transfer(source_knowledge)

    def _apply_transfer(self, source):
        """Apply source knowledge with structural similarity weighting."""
        source_graph = source.get('graph')
        target_graph = self.env.graph

        # Compute structural similarity
        if source_graph:
            self.transfer_weight = self._structural_similarity(
                source_graph, target_graph
            )
        else:
            self.transfer_weight = 0.5

        # Transfer arm estimates weighted by similarity
        arm_estimates = source.get('arm_estimates', [])
        for arm in range(min(self.k, len(arm_estimates))):
            mean, count = arm_estimates[arm]
            # Virtual counts from source, discounted by similarity
            virtual_count = count * self.transfer_weight
            self.counts[arm] = int(virtual_count)
            self.reward_sums[arm] = mean * virtual_count
            self.total += int(virtual_count)

    def _structural_similarity(self, g1, g2):
        """Compute structural similarity between two causal graphs."""
        nodes1 = set(g1.nodes)
        nodes2 = set(g2.nodes)
        common = nodes1 & nodes2
        if not common:
            return 0.0

        # Jaccard on nodes
        node_sim = len(common) / len(nodes1 | nodes2)

        # Edge overlap on common nodes
        edges1 = set((p, c) for p, c in g1.edges if p in common and c in common)
        edges2 = set((p, c) for p, c in g2.edges if p in common and c in common)
        if edges1 or edges2:
            edge_sim = len(edges1 & edges2) / len(edges1 | edges2)
        else:
            edge_sim = 1.0 if not edges1 and not edges2 else 0.0

        return 0.5 * node_sim + 0.5 * edge_sim

    def select_arm(self, c=2.0):
        for a in range(self.k):
            if self.counts[a] == 0:
                return a
        ucb = []
        for a in range(self.k):
            mean = self.reward_sums[a] / self.counts[a]
            bonus = c * math.sqrt(math.log(self.total) / self.counts[a])
            ucb.append(mean + bonus)
        return max(range(self.k), key=lambda a: ucb[a])

    def update(self, arm, reward):
        self.counts[arm] += 1
        self.reward_sums[arm] += reward
        self.total += 1

    def run(self, n_rounds, c=2.0):
        arms = []
        rewards = []
        regret = []
        cum_regret = 0.0
        opt = self.env.optimal_reward()

        for _ in range(n_rounds):
            arm = self.select_arm(c)
            _, reward = self.env.pull(arm)
            self.update(arm, reward)
            arms.append(arm)
            rewards.append(reward)
            cum_regret += opt - self.env.true_reward(arm)
            regret.append(cum_regret)

        return arms, rewards, regret

    def export_knowledge(self):
        """Export learned knowledge for transfer to another bandit."""
        estimates = []
        for a in range(self.k):
            mean = self.reward_sums[a] / max(1, self.counts[a])
            estimates.append((mean, self.counts[a]))
        return {
            'arm_estimates': estimates,
            'graph': self.env.graph,
            'adjustment_set': BackdoorCriterion.find_adjustment_set(
                self.env.graph, self.env.treatment, self.env.outcome
            )
        }


# ============================================================
# 6. CounterfactualBandit
# ============================================================

class CounterfactualBandit:
    """Uses counterfactual reasoning for regret minimization.

    After each round, reasons: "Would I have gotten a better reward
    if I had chosen a different arm?" Uses twin-network counterfactuals
    from C161 to estimate counterfactual rewards without actually pulling.
    """

    def __init__(self, env, seed=None):
        self.env = env
        self.k = env.k
        self.rng = random.Random(seed)
        self.counts = [0] * self.k
        self.reward_sums = [0.0] * self.k
        self.total = 0

        # Counterfactual reward estimates
        self.cf_counts = [0] * self.k
        self.cf_reward_sums = [0.0] * self.k

        self.engine = CounterfactualEngine(env.graph)

    def select_arm(self, c=2.0):
        """Select arm using combined actual + counterfactual estimates."""
        for a in range(self.k):
            if self.counts[a] + self.cf_counts[a] == 0:
                return a

        ucb = []
        for a in range(self.k):
            total_count = self.counts[a] + self.cf_counts[a]
            total_reward = self.reward_sums[a] + self.cf_reward_sums[a]
            mean = total_reward / max(1, total_count)
            total_pulls = self.total + sum(self.cf_counts)
            bonus = c * math.sqrt(math.log(max(1, total_pulls)) / max(1, total_count))
            ucb.append(mean + bonus)
        return max(range(self.k), key=lambda a: ucb[a])

    def update(self, arm, context, reward):
        """Update with actual reward and counterfactual estimates."""
        self.counts[arm] += 1
        self.reward_sums[arm] += reward
        self.total += 1

        # Compute counterfactual rewards for unchosen arms
        evidence = dict(context)
        evidence[self.env.treatment] = arm
        evidence[self.env.outcome] = reward

        for other_arm in range(self.k):
            if other_arm == arm:
                continue
            try:
                cf_factor = self.engine.query(
                    self.env.outcome,
                    {self.env.treatment: other_arm},
                    evidence
                )
                # Expected counterfactual reward
                card = self.env.graph.cardinalities.get(self.env.outcome, 2)
                cf_reward = 0.0
                for val in range(card):
                    cf_reward += val * cf_factor.get_value({self.env.outcome: val})
                self.cf_counts[other_arm] += 1
                self.cf_reward_sums[other_arm] += cf_reward
            except Exception:
                pass  # Skip if counterfactual query fails

    def run(self, n_rounds, c=2.0):
        arms = []
        rewards = []
        regret = []
        cum_regret = 0.0
        opt = self.env.optimal_reward()

        for _ in range(n_rounds):
            arm = self.select_arm(c)
            context, reward = self.env.pull(arm)
            self.update(arm, context, reward)
            arms.append(arm)
            rewards.append(reward)
            cum_regret += opt - self.env.true_reward(arm)
            regret.append(cum_regret)

        return arms, rewards, regret


# ============================================================
# 7. CausalLinUCB
# ============================================================

class CausalLinUCB:
    """Linear contextual bandit with causal feature selection.

    Uses the causal graph to select only causally relevant features
    (parents of the outcome, not descendants or colliders), avoiding
    the spurious correlations that confound standard contextual bandits.
    """

    def __init__(self, env, alpha=1.0):
        self.env = env
        self.k = env.k
        self.alpha = alpha

        # Select causal features: parents of outcome that aren't descendants of treatment
        self.causal_features = self._select_causal_features()
        self.d = max(1, len(self.causal_features))  # feature dimension

        # LinUCB parameters per arm
        self.A = {}  # d x d identity matrices
        self.b = {}  # d x 1 zero vectors
        for a in range(self.k):
            self.A[a] = [[1.0 if i == j else 0.0 for j in range(self.d)]
                         for i in range(self.d)]
            self.b[a] = [0.0] * self.d

    def _select_causal_features(self):
        """Select causally relevant features using graph structure."""
        graph = self.env.graph
        outcome = self.env.outcome
        treatment = self.env.treatment

        # Get parents of outcome (direct causes)
        parents = set(graph.get_parents(outcome))

        # Get ancestors of outcome (potential confounders)
        ancestors = graph.ancestors(outcome)

        # Exclude treatment and outcome themselves
        candidates = (parents | ancestors) - {treatment, outcome}

        # Exclude descendants of treatment (mediators can induce bias if conditioned on)
        descendants_of_treatment = graph.descendants(treatment)

        # Safe features: ancestors of outcome that aren't descendants of treatment
        safe = candidates - descendants_of_treatment

        # If nothing safe, use observable parents
        if not safe:
            safe = parents - {treatment, outcome}

        # Intersect with observable variables
        features = sorted(safe & self.env.observable)
        return features if features else sorted(self.env.observable)[:1]

    def _get_feature_vector(self, context):
        """Extract causal feature vector from context."""
        return [float(context.get(f, 0)) for f in self.causal_features]

    def select_arm(self, context):
        """Select arm using LinUCB with causal features."""
        x = self._get_feature_vector(context)
        ucb_values = []

        for a in range(self.k):
            # Compute A_inv * x
            A_inv = self._matrix_inverse(self.A[a])
            theta = self._mat_vec(A_inv, self.b[a])
            pred = sum(theta[i] * x[i] for i in range(self.d))

            # Confidence bonus: sqrt(x^T A_inv x)
            Ax = self._mat_vec(A_inv, x)
            var = sum(x[i] * Ax[i] for i in range(self.d))
            bonus = self.alpha * math.sqrt(max(0, var))

            ucb_values.append(pred + bonus)

        return max(range(self.k), key=lambda a: ucb_values[a])

    def update(self, arm, context, reward):
        """Update LinUCB parameters."""
        x = self._get_feature_vector(context)

        # A += x * x^T
        for i in range(self.d):
            for j in range(self.d):
                self.A[arm][i][j] += x[i] * x[j]

        # b += reward * x
        for i in range(self.d):
            self.b[arm][i] += reward * x[i]

    def _matrix_inverse(self, M):
        """Simple matrix inverse for small matrices."""
        n = len(M)
        if n == 1:
            return [[1.0 / M[0][0]]] if M[0][0] != 0 else [[1e10]]

        # Augmented matrix [M | I]
        aug = [row[:] + [1.0 if i == j else 0.0 for j in range(n)]
               for i, row in enumerate(M)]

        for col in range(n):
            # Pivot
            max_row = max(range(col, n), key=lambda r: abs(aug[r][col]))
            aug[col], aug[max_row] = aug[max_row], aug[col]

            pivot = aug[col][col]
            if abs(pivot) < 1e-12:
                aug[col][col] = 1e-12
                pivot = 1e-12

            for j in range(2 * n):
                aug[col][j] /= pivot

            for row in range(n):
                if row != col:
                    factor = aug[row][col]
                    for j in range(2 * n):
                        aug[row][j] -= factor * aug[col][j]

        return [row[n:] for row in aug]

    def _mat_vec(self, M, v):
        """Matrix-vector product."""
        return [sum(M[i][j] * v[j] for j in range(len(v))) for i in range(len(M))]

    def run(self, n_rounds):
        arms = []
        rewards = []
        regret = []
        cum_regret = 0.0
        opt = self.env.optimal_reward()

        for _ in range(n_rounds):
            # Get context from an observation
            context, _ = self.env.pull(0)  # Pull arm 0 just for context
            arm = self.select_arm(context)
            _, reward = self.env.pull(arm)
            self.update(arm, context, reward)
            arms.append(arm)
            rewards.append(reward)
            cum_regret += opt - self.env.true_reward(arm)
            regret.append(cum_regret)

        return arms, rewards, regret


# ============================================================
# 8. BudgetedCausalBandit
# ============================================================

class BudgetedCausalBandit:
    """Bandit where interventions have costs. Optimize net reward (reward - cost).

    Different intervention targets have different costs. Observing (no intervention)
    is free but yields confounded data. The agent balances intervention cost
    against information gain.
    """

    def __init__(self, env, intervention_costs=None, observation_budget=0.5):
        """
        Args:
            env: CausalBanditEnv
            intervention_costs: dict mapping arm -> cost (default: uniform cost 0.1)
            observation_budget: fraction of rounds to allocate to free observations
        """
        self.env = env
        self.k = env.k
        self.observation_budget = observation_budget

        if intervention_costs is None:
            self.costs = {a: 0.1 for a in range(self.k)}
        else:
            self.costs = dict(intervention_costs)

        self.counts = [0] * self.k
        self.reward_sums = [0.0] * self.k
        self.cost_spent = 0.0
        self.total = 0

        # Observational data for free learning
        self.obs_counts = defaultdict(int)
        self.obs_reward_sums = defaultdict(float)

    def select_arm(self, budget_remaining, c=2.0):
        """Select arm considering cost-effectiveness."""
        # Decide whether to observe (free) or intervene (costly)
        if self.total > 0 and self.rng.random() < self.observation_budget:
            return -1  # Signal to observe instead

        for a in range(self.k):
            if self.counts[a] == 0:
                return a

        # Cost-adjusted UCB: (reward - cost) / cost for efficiency
        ucb = []
        for a in range(self.k):
            mean = self.reward_sums[a] / self.counts[a]
            net = mean - self.costs.get(a, 0)
            bonus = c * math.sqrt(math.log(self.total) / self.counts[a])
            ucb.append(net + bonus)
        return max(range(self.k), key=lambda a: ucb[a])

    def update_intervention(self, arm, reward):
        self.counts[arm] += 1
        self.reward_sums[arm] += reward
        self.cost_spent += self.costs.get(arm, 0)
        self.total += 1

    def update_observation(self, obs_data):
        """Learn from free observational data."""
        treatment_val = obs_data.get(self.env.treatment)
        outcome_val = obs_data.get(self.env.outcome)
        if treatment_val is not None and outcome_val is not None:
            self.obs_counts[treatment_val] += 1
            self.obs_reward_sums[treatment_val] += outcome_val

    def run(self, n_rounds, budget=None, c=2.0):
        """Run with optional total budget constraint."""
        self.rng = random.Random(42)
        arms = []
        rewards = []
        net_rewards = []
        cum_net = 0.0

        for _ in range(n_rounds):
            if budget is not None and self.cost_spent >= budget:
                # Budget exhausted -- observe only
                obs = self.env.observe()
                self.update_observation(obs)
                arms.append(-1)
                rewards.append(0)
                net_rewards.append(cum_net)
                continue

            arm = self.select_arm(budget, c)
            if arm == -1:
                obs = self.env.observe()
                self.update_observation(obs)
                arms.append(-1)
                rewards.append(0)
                net_rewards.append(cum_net)
            else:
                _, reward = self.env.pull(arm)
                self.update_intervention(arm, reward)
                net = reward - self.costs.get(arm, 0)
                cum_net += net
                arms.append(arm)
                rewards.append(reward)
                net_rewards.append(cum_net)

        return arms, rewards, net_rewards

    def best_cost_effective_arm(self):
        """Return arm with best observed net reward."""
        best = -1
        best_net = float('-inf')
        for a in range(self.k):
            if self.counts[a] > 0:
                mean = self.reward_sums[a] / self.counts[a]
                net = mean - self.costs.get(a, 0)
                if net > best_net:
                    best_net = net
                    best = a
        return best


# ============================================================
# 9. CausalBanditAnalyzer
# ============================================================

class CausalBanditAnalyzer:
    """Analyze and compare causal bandit algorithms."""

    @staticmethod
    def compute_regret(arms, env):
        """Compute cumulative regret for a sequence of arm pulls."""
        opt = env.optimal_reward()
        regret = []
        cum = 0.0
        for arm in arms:
            cum += opt - env.true_reward(arm)
            regret.append(cum)
        return regret

    @staticmethod
    def arm_distribution(arms, k):
        """Compute fraction of times each arm was pulled."""
        counts = [0] * k
        for a in arms:
            if 0 <= a < k:
                counts[a] += 1
        total = sum(counts)
        if total == 0:
            return [0.0] * k
        return [c / total for c in counts]

    @staticmethod
    def compare_algorithms(env, algorithms, n_rounds, n_trials=5):
        """Compare multiple algorithms over multiple trials.

        Args:
            env: CausalBanditEnv (will be reseeded each trial)
            algorithms: dict of name -> factory function (takes env, returns bandit)
            n_rounds: rounds per trial
            n_trials: number of independent trials

        Returns:
            dict of name -> {
                'mean_regret': final mean cumulative regret,
                'std_regret': std of final cumulative regret,
                'mean_arm_dist': average arm distribution,
                'optimal_arm_frac': fraction of times optimal arm chosen
            }
        """
        results = {}
        opt_arm = env.optimal_arm()

        for name, factory in algorithms.items():
            final_regrets = []
            arm_dists = []
            opt_fracs = []

            for trial in range(n_trials):
                env.rng = random.Random(trial * 1000)
                bandit = factory(env)

                if hasattr(bandit, 'run'):
                    arms, rewards, regret = bandit.run(n_rounds)
                else:
                    arms = []
                    rewards = []
                    regret = []
                    cum_r = 0.0
                    for _ in range(n_rounds):
                        arm = bandit.select_arm()
                        _, reward = env.pull(arm)
                        bandit.update(arm, reward)
                        arms.append(arm)
                        rewards.append(reward)
                        cum_r += env.optimal_reward() - env.true_reward(arm)
                        regret.append(cum_r)

                final_regrets.append(regret[-1] if regret else 0)
                arm_dists.append(CausalBanditAnalyzer.arm_distribution(arms, env.k))
                opt_count = sum(1 for a in arms if a == opt_arm)
                opt_fracs.append(opt_count / len(arms) if arms else 0)

            mean_regret = sum(final_regrets) / len(final_regrets)
            mean_sq = sum(r**2 for r in final_regrets) / len(final_regrets)
            std_regret = math.sqrt(max(0, mean_sq - mean_regret**2))

            mean_dist = [0.0] * env.k
            for dist in arm_dists:
                for a in range(env.k):
                    mean_dist[a] += dist[a]
            mean_dist = [d / n_trials for d in mean_dist]

            results[name] = {
                'mean_regret': mean_regret,
                'std_regret': std_regret,
                'mean_arm_dist': mean_dist,
                'optimal_arm_frac': sum(opt_fracs) / len(opt_fracs),
            }

        return results

    @staticmethod
    def causal_advantage(env, n_rounds=200, n_trials=5):
        """Measure the advantage of causal methods over standard UCB.

        Returns ratio of standard UCB regret to causal UCB regret.
        Ratio > 1 means causal method is better.
        """
        std_regrets = []
        causal_regrets = []

        for trial in range(n_trials):
            # Standard UCB (no causal adjustment)
            env.rng = random.Random(trial * 100)
            std_ucb = CausalUCB(env, c=2.0)
            std_ucb.use_causal = False  # Disable causal adjustment
            _, _, std_reg = std_ucb.run(n_rounds)
            std_regrets.append(std_reg[-1] if std_reg else 0)

            # Causal UCB
            env.rng = random.Random(trial * 100)
            causal_ucb = CausalUCB(env, c=2.0)
            _, _, causal_reg = causal_ucb.run(n_rounds)
            causal_regrets.append(causal_reg[-1] if causal_reg else 0)

        mean_std = sum(std_regrets) / max(1, len(std_regrets))
        mean_causal = sum(causal_regrets) / max(1, len(causal_regrets))

        return {
            'standard_regret': mean_std,
            'causal_regret': mean_causal,
            'advantage_ratio': mean_std / mean_causal if mean_causal > 0 else float('inf'),
        }


# ============================================================
# Helper: Build standard test graphs
# ============================================================

def make_confounded_graph(p_confounder=0.5, p_treat_given_conf=None, p_outcome_given_treat_conf=None):
    """Create a simple confounded graph: U -> X, U -> Y, X -> Y.

    U is the confounder, X is treatment, Y is outcome.
    Returns CausalGraph with CPDs.
    """
    g = CausalGraph()
    g.add_node('U', cardinality=2)
    g.add_node('X', cardinality=2)
    g.add_node('Y', cardinality=2)
    g.add_edge('U', 'X')
    g.add_edge('U', 'Y')
    g.add_edge('X', 'Y')

    # P(U)
    u_cpd = Factor(['U'], {'U': 2})
    u_cpd.set_value({'U': 0}, 1 - p_confounder)
    u_cpd.set_value({'U': 1}, p_confounder)
    g.set_cpd('U', u_cpd)

    # P(X | U)
    if p_treat_given_conf is None:
        p_treat_given_conf = {(0,): 0.2, (1,): 0.8}
    x_cpd = Factor(['X', 'U'], {'X': 2, 'U': 2})
    x_cpd.set_value({'X': 0, 'U': 0}, 1 - p_treat_given_conf[(0,)])
    x_cpd.set_value({'X': 1, 'U': 0}, p_treat_given_conf[(0,)])
    x_cpd.set_value({'X': 0, 'U': 1}, 1 - p_treat_given_conf[(1,)])
    x_cpd.set_value({'X': 1, 'U': 1}, p_treat_given_conf[(1,)])
    g.set_cpd('X', x_cpd)

    # P(Y | X, U)
    if p_outcome_given_treat_conf is None:
        p_outcome_given_treat_conf = {
            (0, 0): 0.1, (1, 0): 0.5,  # U=0: treatment helps
            (0, 1): 0.3, (1, 1): 0.9,  # U=1: treatment helps more
        }
    y_cpd = Factor(['Y', 'X', 'U'], {'Y': 2, 'X': 2, 'U': 2})
    for (x, u), p in p_outcome_given_treat_conf.items():
        y_cpd.set_value({'Y': 1, 'X': x, 'U': u}, p)
        y_cpd.set_value({'Y': 0, 'X': x, 'U': u}, 1 - p)
    g.set_cpd('Y', y_cpd)

    return g


def make_mediator_graph():
    """Create a mediated graph: X -> M -> Y with confounder U -> {X, Y}.

    Frontdoor criterion applies through M.
    """
    g = CausalGraph()
    g.add_node('U', cardinality=2)
    g.add_node('X', cardinality=2)
    g.add_node('M', cardinality=2)
    g.add_node('Y', cardinality=2)
    g.add_edge('U', 'X')
    g.add_edge('U', 'Y')
    g.add_edge('X', 'M')
    g.add_edge('M', 'Y')

    # P(U)
    u_cpd = Factor(['U'], {'U': 2})
    u_cpd.set_value({'U': 0}, 0.5)
    u_cpd.set_value({'U': 1}, 0.5)
    g.set_cpd('U', u_cpd)

    # P(X | U)
    x_cpd = Factor(['X', 'U'], {'X': 2, 'U': 2})
    x_cpd.set_value({'X': 0, 'U': 0}, 0.8)
    x_cpd.set_value({'X': 1, 'U': 0}, 0.2)
    x_cpd.set_value({'X': 0, 'U': 1}, 0.3)
    x_cpd.set_value({'X': 1, 'U': 1}, 0.7)
    g.set_cpd('X', x_cpd)

    # P(M | X)
    m_cpd = Factor(['M', 'X'], {'M': 2, 'X': 2})
    m_cpd.set_value({'M': 0, 'X': 0}, 0.9)
    m_cpd.set_value({'M': 1, 'X': 0}, 0.1)
    m_cpd.set_value({'M': 0, 'X': 1}, 0.2)
    m_cpd.set_value({'M': 1, 'X': 1}, 0.8)
    g.set_cpd('M', m_cpd)

    # P(Y | M, U)
    y_cpd = Factor(['Y', 'M', 'U'], {'Y': 2, 'M': 2, 'U': 2})
    y_cpd.set_value({'Y': 1, 'M': 0, 'U': 0}, 0.1)
    y_cpd.set_value({'Y': 0, 'M': 0, 'U': 0}, 0.9)
    y_cpd.set_value({'Y': 1, 'M': 1, 'U': 0}, 0.7)
    y_cpd.set_value({'Y': 0, 'M': 1, 'U': 0}, 0.3)
    y_cpd.set_value({'Y': 1, 'M': 0, 'U': 1}, 0.3)
    y_cpd.set_value({'Y': 0, 'M': 0, 'U': 1}, 0.7)
    y_cpd.set_value({'Y': 1, 'M': 1, 'U': 1}, 0.9)
    y_cpd.set_value({'Y': 0, 'M': 1, 'U': 1}, 0.1)
    g.set_cpd('Y', y_cpd)

    return g


def make_instrument_graph():
    """Create an instrumental variable graph: Z -> X -> Y, U -> {X, Y}.

    Z is the instrument (affects X but not Y directly).
    """
    g = CausalGraph()
    g.add_node('Z', cardinality=2)
    g.add_node('U', cardinality=2)
    g.add_node('X', cardinality=2)
    g.add_node('Y', cardinality=2)
    g.add_edge('Z', 'X')
    g.add_edge('U', 'X')
    g.add_edge('U', 'Y')
    g.add_edge('X', 'Y')

    # P(Z)
    z_cpd = Factor(['Z'], {'Z': 2})
    z_cpd.set_value({'Z': 0}, 0.5)
    z_cpd.set_value({'Z': 1}, 0.5)
    g.set_cpd('Z', z_cpd)

    # P(U)
    u_cpd = Factor(['U'], {'U': 2})
    u_cpd.set_value({'U': 0}, 0.5)
    u_cpd.set_value({'U': 1}, 0.5)
    g.set_cpd('U', u_cpd)

    # P(X | Z, U)
    x_cpd = Factor(['X', 'Z', 'U'], {'X': 2, 'Z': 2, 'U': 2})
    x_cpd.set_value({'X': 0, 'Z': 0, 'U': 0}, 0.9)
    x_cpd.set_value({'X': 1, 'Z': 0, 'U': 0}, 0.1)
    x_cpd.set_value({'X': 0, 'Z': 1, 'U': 0}, 0.3)
    x_cpd.set_value({'X': 1, 'Z': 1, 'U': 0}, 0.7)
    x_cpd.set_value({'X': 0, 'Z': 0, 'U': 1}, 0.7)
    x_cpd.set_value({'X': 1, 'Z': 0, 'U': 1}, 0.3)
    x_cpd.set_value({'X': 0, 'Z': 1, 'U': 1}, 0.1)
    x_cpd.set_value({'X': 1, 'Z': 1, 'U': 1}, 0.9)
    g.set_cpd('X', x_cpd)

    # P(Y | X, U)
    y_cpd = Factor(['Y', 'X', 'U'], {'Y': 2, 'X': 2, 'U': 2})
    y_cpd.set_value({'Y': 1, 'X': 0, 'U': 0}, 0.2)
    y_cpd.set_value({'Y': 0, 'X': 0, 'U': 0}, 0.8)
    y_cpd.set_value({'Y': 1, 'X': 1, 'U': 0}, 0.6)
    y_cpd.set_value({'Y': 0, 'X': 1, 'U': 0}, 0.4)
    y_cpd.set_value({'Y': 1, 'X': 0, 'U': 1}, 0.4)
    y_cpd.set_value({'Y': 0, 'X': 0, 'U': 1}, 0.6)
    y_cpd.set_value({'Y': 1, 'X': 1, 'U': 1}, 0.8)
    y_cpd.set_value({'Y': 0, 'X': 1, 'U': 1}, 0.2)
    g.set_cpd('Y', y_cpd)

    return g
