"""
V051: Counterexample-Guided Optimization Verification (CEGOV)

Composes V049 (verified compilation) + V001 (guided symbolic execution).
When translation validation fails for an optimization pass, this module:

1. Extracts the counterexample from V049's failed proof obligation
2. Uses V001 guided symbolic execution to generate concrete test inputs
   that exercise the optimization boundary
3. Cross-validates: executes the program with and without optimization
   using the counterexample inputs to confirm/refute the failure
4. Generates a diagnostic report with root cause classification

This implements a CEGAR-like loop at the compilation level:
  Validate -> Counterexample -> Guided Testing -> Refine Understanding
"""

import sys
import os
import traceback
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional, List, Dict, Any, Tuple

# Add paths
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..', 'challenges', 'C010_stack_vm'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..', 'challenges', 'C014_bytecode_optimizer'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..', 'challenges', 'C037_smt_solver'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..', 'challenges', 'C038_symbolic_execution'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', '..', 'challenges', 'C039_abstract_interpreter'))

_work = os.path.join(os.path.dirname(__file__), '..')

def _add_vpath(name):
    p = os.path.join(_work, name)
    if p not in sys.path:
        sys.path.insert(0, p)

_add_vpath('V001_guided_symbolic_execution')
_add_vpath('V049_verified_compilation')
_add_vpath('V044_proof_certificates')


# --- Result Types ---

class FailureKind(Enum):
    """Classification of optimization failure."""
    CONFIRMED_BUG = "confirmed_bug"       # Counterexample reproduces: real optimizer bug
    SPURIOUS = "spurious"                  # Counterexample doesn't reproduce: validation imprecision
    BOUNDARY_CASE = "boundary_case"       # Edge case at optimization boundary (e.g., overflow)
    UNREACHABLE = "unreachable"            # Counterexample inputs are infeasible in practice
    UNKNOWN = "unknown"


@dataclass
class CounterexampleDiag:
    """Diagnostic information about a single counterexample."""
    pass_name: str
    obligation_name: str
    raw_counterexample: Optional[dict]       # From V049's SMT model
    concrete_inputs: Dict[str, Any]          # Extracted concrete values
    unoptimized_result: Any = None           # Result without optimization
    optimized_result: Any = None             # Result with optimization
    results_match: Optional[bool] = None     # Do they produce same output?
    kind: FailureKind = FailureKind.UNKNOWN
    description: str = ""


@dataclass
class GuidedTestCase:
    """A test case generated by guided symbolic execution."""
    inputs: Dict[str, Any]
    path_condition: str = ""
    covers_boundary: bool = False  # True if this test case exercises the optimization edge


@dataclass
class CEGOVResult:
    """Result of counterexample-guided optimization verification."""
    source: str
    validation_passed: bool                               # Did V049 pass?
    counterexamples: List[CounterexampleDiag] = field(default_factory=list)
    guided_tests: List[GuidedTestCase] = field(default_factory=list)
    confirmed_bugs: int = 0
    spurious_failures: int = 0
    total_obligations: int = 0
    failed_obligations: int = 0

    @property
    def has_real_bugs(self) -> bool:
        return self.confirmed_bugs > 0

    @property
    def all_spurious(self) -> bool:
        return self.failed_obligations > 0 and self.confirmed_bugs == 0

    def summary(self) -> str:
        lines = []
        lines.append("CEGOV Report")
        lines.append("-" * 40)
        lines.append(f"Validation: {'PASSED' if self.validation_passed else 'FAILED'}")
        lines.append(f"Obligations: {self.total_obligations} total, {self.failed_obligations} failed")
        if self.counterexamples:
            lines.append(f"Counterexamples: {len(self.counterexamples)}")
            lines.append(f"  Confirmed bugs: {self.confirmed_bugs}")
            lines.append(f"  Spurious: {self.spurious_failures}")
            for cex in self.counterexamples:
                lines.append(f"  [{cex.kind.value}] {cex.pass_name}/{cex.obligation_name}: {cex.description}")
        if self.guided_tests:
            boundary = sum(1 for t in self.guided_tests if t.covers_boundary)
            lines.append(f"Guided tests: {len(self.guided_tests)} ({boundary} boundary-covering)")
        return "\n".join(lines)


# --- Core Logic ---

def _extract_counterexample_inputs(cex: dict) -> Dict[str, Any]:
    """Extract concrete variable assignments from an SMT counterexample model."""
    if not cex:
        return {}
    # Filter out internal variables (starting with __)
    return {k: v for k, v in cex.items() if not k.startswith('__')}


def _execute_program(source: str) -> Any:
    """Execute a C10 program and capture its output/return value."""
    try:
        from stack_vm import lex, Parser, Compiler, VM
        tokens = lex(source)
        program = Parser(tokens).parse()
        compiler = Compiler()
        chunk = compiler.compile(program)
        vm = VM(chunk)
        result = vm.run()
        return {"output": vm.output if hasattr(vm, 'output') else None,
                "result": result, "error": None}
    except Exception as e:
        return {"output": None, "result": None, "error": str(e)}


def _execute_optimized(source: str) -> Any:
    """Execute a C10 program with optimization and capture output."""
    try:
        from optimizer import optimize_source, execute_optimized
        result = execute_optimized(source)
        return {"output": result.get('output'), "result": result.get('result'),
                "error": result.get('error')}
    except Exception as e:
        try:
            # Fallback: compile, optimize, run manually
            from stack_vm import lex, Parser, Compiler, VM
            from optimizer import optimize_chunk
            tokens = lex(source)
            program = Parser(tokens).parse()
            compiler = Compiler()
            chunk = compiler.compile(program)
            opt_chunk = optimize_chunk(chunk)
            vm = VM(opt_chunk)
            result = vm.run()
            return {"output": vm.output if hasattr(vm, 'output') else None,
                    "result": result, "error": None}
        except Exception as e2:
            return {"output": None, "result": None, "error": str(e2)}


def _classify_counterexample(cex_diag: CounterexampleDiag) -> FailureKind:
    """Classify a counterexample based on cross-validation results."""
    if cex_diag.results_match is None:
        return FailureKind.UNKNOWN
    if cex_diag.results_match:
        # Outputs are the same -> the counterexample is spurious
        # (validation was imprecise but the optimization is actually correct)
        return FailureKind.SPURIOUS
    else:
        # Outputs differ -> real bug in the optimization
        return FailureKind.CONFIRMED_BUG


def _make_test_program(source: str, inputs: Dict[str, Any]) -> str:
    """Embed concrete input values into a program for testing.

    For each variable in inputs, prepend a `let var = value;` line.
    This is a best-effort approach for simple programs.
    """
    prefix_lines = []
    for var, val in inputs.items():
        if isinstance(val, bool):
            prefix_lines.append(f"let {var} = {'true' if val else 'false'};")
        elif isinstance(val, (int, float)):
            if val < 0:
                prefix_lines.append(f"let {var} = 0 - {abs(int(val))};")
            else:
                prefix_lines.append(f"let {var} = {int(val)};")
    if prefix_lines:
        return "\n".join(prefix_lines) + "\n" + source
    return source


def _cross_validate_counterexample(
    source: str, cex: dict, pass_name: str, obligation_name: str
) -> CounterexampleDiag:
    """Cross-validate a counterexample by executing with and without optimization."""
    inputs = _extract_counterexample_inputs(cex)

    diag = CounterexampleDiag(
        pass_name=pass_name,
        obligation_name=obligation_name,
        raw_counterexample=cex,
        concrete_inputs=inputs,
    )

    # Execute original and optimized
    unopt = _execute_program(source)
    opt = _execute_optimized(source)

    diag.unoptimized_result = unopt
    diag.optimized_result = opt

    # Compare results
    if unopt.get('error') and opt.get('error'):
        # Both error -> match (same behavior)
        diag.results_match = True
    elif unopt.get('error') or opt.get('error'):
        # One errors, other doesn't -> mismatch
        diag.results_match = False
    else:
        # Compare outputs
        diag.results_match = (unopt.get('result') == opt.get('result'))

    diag.kind = _classify_counterexample(diag)
    diag.description = (
        f"inputs={inputs}, match={diag.results_match}"
        if inputs else f"no extractable inputs, match={diag.results_match}"
    )

    return diag


def _generate_guided_tests(source: str) -> List[GuidedTestCase]:
    """Use V001 guided symbolic execution to generate test cases."""
    try:
        from guided_symbolic import guided_execute
        result = guided_execute(source)

        tests = []
        if hasattr(result, 'execution') and result.execution:
            exec_r = result.execution
            if hasattr(exec_r, 'completed_paths'):
                for p in exec_r.completed_paths:
                    inputs = {}
                    pc_str = ""
                    if hasattr(p, 'model') and p.model:
                        inputs = dict(p.model)
                    if hasattr(p, 'constraints') and p.constraints:
                        pc_str = str(p.constraints)
                    tests.append(GuidedTestCase(
                        inputs=inputs,
                        path_condition=pc_str,
                        covers_boundary=False,  # Set later by boundary analysis
                    ))
        return tests
    except Exception:
        return []


def _check_boundary_coverage(tests: List[GuidedTestCase], cex_inputs: List[Dict]) -> None:
    """Mark tests that exercise inputs near counterexample boundaries."""
    for test in tests:
        for cex_in in cex_inputs:
            if not cex_in:
                continue
            # A test covers the boundary if its inputs are "close" to the cex
            for var, cex_val in cex_in.items():
                test_val = test.inputs.get(var)
                if test_val is not None and isinstance(cex_val, (int, float)):
                    if isinstance(test_val, (int, float)):
                        if abs(test_val - cex_val) <= 1:
                            test.covers_boundary = True
                            break


# --- Main API ---

def analyze_cegov(source: str) -> CEGOVResult:
    """
    Run Counterexample-Guided Optimization Verification.

    1. Validate compilation via V049
    2. Extract counterexamples from failed obligations
    3. Cross-validate each counterexample
    4. Generate guided test cases via V001
    5. Classify failures and produce diagnostic report

    Args:
        source: C10 program source code

    Returns:
        CEGOVResult with diagnostics
    """
    from verified_compilation import validate_compilation
    from proof_certificates import CertStatus

    result = CEGOVResult(source=source, validation_passed=True)

    # Step 1: Validate compilation
    val = validate_compilation(source)

    # Count obligations
    for pr in val.pass_results:
        result.total_obligations += len(pr.obligations)
        for ob in pr.obligations:
            if ob.status != CertStatus.VALID:
                result.failed_obligations += 1

    result.validation_passed = val.is_valid

    # Step 2: Extract and cross-validate counterexamples
    if not val.is_valid:
        for pr in val.pass_results:
            pass_name = pr.pass_name.value if hasattr(pr.pass_name, 'value') else str(pr.pass_name)
            for ob in pr.obligations:
                if ob.status != CertStatus.VALID and ob.counterexample:
                    diag = _cross_validate_counterexample(
                        source, ob.counterexample, pass_name, ob.name
                    )
                    result.counterexamples.append(diag)
                    if diag.kind == FailureKind.CONFIRMED_BUG:
                        result.confirmed_bugs += 1
                    elif diag.kind == FailureKind.SPURIOUS:
                        result.spurious_failures += 1

    # Step 3: Generate guided test cases
    tests = _generate_guided_tests(source)
    if tests:
        # Check boundary coverage against counterexample inputs
        cex_inputs = [d.concrete_inputs for d in result.counterexamples]
        _check_boundary_coverage(tests, cex_inputs)
        result.guided_tests = tests

    return result


def validate_and_diagnose(source: str) -> str:
    """Run CEGOV and return human-readable summary."""
    result = analyze_cegov(source)
    return result.summary()


def check_pass_with_cex(source: str, pass_name: str) -> CEGOVResult:
    """
    Validate a single optimization pass and diagnose any counterexamples.

    Args:
        source: C10 program source code
        pass_name: Name of the optimization pass (e.g., "constant_fold")

    Returns:
        CEGOVResult focused on the specified pass
    """
    from verified_compilation import validate_pass, PassName
    from proof_certificates import CertStatus

    # Map string to PassName enum
    pn = None
    for p in PassName:
        if p.value == pass_name:
            pn = p
            break
    if pn is None:
        result = CEGOVResult(source=source, validation_passed=False)
        return result

    pr = validate_pass(source, pn)

    result = CEGOVResult(source=source, validation_passed=True)
    result.total_obligations = len(pr.obligations)

    for ob in pr.obligations:
        if ob.status != CertStatus.VALID:
            result.failed_obligations += 1
            result.validation_passed = False
            if ob.counterexample:
                diag = _cross_validate_counterexample(
                    source, ob.counterexample,
                    pass_name, ob.name
                )
                result.counterexamples.append(diag)
                if diag.kind == FailureKind.CONFIRMED_BUG:
                    result.confirmed_bugs += 1
                elif diag.kind == FailureKind.SPURIOUS:
                    result.spurious_failures += 1

    return result


def compare_optimization_behavior(source: str) -> Dict[str, Any]:
    """
    Simple comparison of optimized vs unoptimized execution.

    Returns a dict with:
      - match: bool
      - unoptimized: execution result
      - optimized: execution result
    """
    unopt = _execute_program(source)
    opt = _execute_optimized(source)

    if unopt.get('error') and opt.get('error'):
        match = True
    elif unopt.get('error') or opt.get('error'):
        match = False
    else:
        match = (unopt.get('result') == opt.get('result'))

    return {
        "match": match,
        "unoptimized": unopt,
        "optimized": opt,
    }
